### ISSUE TITLE
Question for Project Owner - Version of Browsers Used

### ISSUE THREAD

**Issue by MarckK** [RoundaboutSheffield/Roundabout#13]
We were wondering which browsers were being used, and therefore we should support. E.g. Chrome, Firefox, Safari, Internet Explorer... just to name a few. As well as this, could you also let us know the version that you are currently using.

If you do not know, please let us know.

**Comment by benkeegan** [comment]
We use firefox and chrome. All were updated with latest versions in July 2016, but we can update again if needed?

**Comment by ghost** [comment]
Thank you @benkeegan. You don't need to update your versions; we just needed to know so we could adapt accordingly.
