### ISSUE TITLE
Add Ellie to stand-ups

### ISSUE THREAD

**Issue by eghale** [RoundaboutSheffield/Roundabout#20]

**Comment by ghost** [comment]
@eghale are you going to be coming in this morning? :)

**Comment by eghale** [comment]
Sorry I realised my GitHub updates were all going to my personal email, which is linked with Github, not my CAST email! I had meetings today and do tomorrow morning but looks like everyone is progressing nicely in my absence :)

Planning on heading over to you guys tomorrow afternoon, but let me know if there's a stand-up or two I could join in the morning as well. Sorry I missed today's!
