### ISSUE TITLE
Reminder of Sprint starting

### ISSUE THREAD

**Issue by ghost** [RoundaboutSheffield/Roundabout#21]
Hi everyone :) I just wanted to remind you all that we are starting the projects this week, and that we would love to be able to talk about the project as it goes along.

I hope you all had a lovely weekend, and we are all very excited to get started with the project.

**Comment by TonyRoundabout** [comment]
Hi Emma,

We're ready to go.  Pocket V is trying to sign in but I'm sure she'll manage it at some point in the near future!

**Comment by PocketV** [comment]
I'm in
