### ISSUE TITLE
Help for demonstration of project

### ISSUE THREAD

**Issue by ghost** [RoundaboutSheffield/Roundabout#28]
Hi everyone - i hope you have had a good week. :)

We would love to show you the MVP we have produced during this sprint, but we would love to have a few of your mobile numbers, so that we can show you and demonstrate how the project runs.

Ideally, we would love to do this today, but we are aware that this might be too soon for you. If you are able to, please get back to us as soon as you can. Thank you :)

**Comment by benkeegan** [comment]
Thanks Emma 

My mobile number is Ben XXXXX , Rose  is XXXXXX , Vanessa is XXXXX and Tony is XXXX

Ben

**Comment by ghost** [comment]
Thank you @benkeegan :) Would you, or the team, be available to Skype to us to chat either today or Monday? :)

**Comment by benkeegan** [comment]
I am available this afternoon to skype.

**Comment by ghost** [comment]
Would Monday be easier for the rest of the P.O. team?

**Comment by benkeegan** [comment]
They are out and about at the moment...so yes Monday would probably be better for us all.

**Comment by ghost** [comment]
That would be better for us actually as well :) Monday morning suitable for you all?

**Comment by benkeegan** [comment]
Hi sorry, do you still need us today? Would 2pm be ok? Or we can do tomorrow at 10am?

**Comment by TonyRoundabout** [comment]
Hi guys, V will be in the office tomorrow at 11:30, so I'll show her how to log on etc then, and Ben if he is in the office.  
So is it possible for the time to be changed to GMT for appointments and for numbers to be input without +44?  The +44 is not so much of an issue but would be good if not too difficult.

**Comment by TonyRoundabout** [comment]
Also the NEXMO thing, is that something you guys will need to do with each person, the code with the 5 minute window, or can we set that up so we can input them ourselves?
