### ISSUE TITLE
Should body of text message be set from task?

### ISSUE THREAD

**Issue by matthewglover** [RoundaboutSheffield/Roundabout#51]

**Comment by daymos** [comment]
In short yes. 
In the onPostEvent handler we have to add a code to the body, to be used by the tenant to reply. Like, "sent a reply to this message with 0001 when you have completed the task". I could add the task description as well. However, the risk is that the admin will add it manually, so we'll have a duplicate. So in the end I think its a good idea to add it.

**Comment by matthewglover** [comment]
Set body of text message as task details
